<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="45736" started-at="2021-11-28T14:59:19 IST" finished-at="2021-11-28T15:00:05 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="45736" started-at="2021-11-28T14:59:19 IST" finished-at="2021-11-28T15:00:05 IST">
      <class name="demo.Home">
        <test-method status="PASS" signature="login(java.lang.String,java.lang.String)[pri:0, instance:demo.Home@34bde49d]" name="login" duration-ms="23075" started-at="2021-11-28T14:59:19 IST" data-provider="getData" finished-at="2021-11-28T14:59:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[pmrreddypmr@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Powertrain@10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="login(java.lang.String,java.lang.String)[pri:0, instance:demo.Home@34bde49d]" name="login" duration-ms="13742" started-at="2021-11-28T14:59:42 IST" data-provider="getData" finished-at="2021-11-28T14:59:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[pmrreddypmr@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Powertrain@20]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="validateTitle()[pri:0, instance:demo.Home@34bde49d]" name="validateTitle" duration-ms="8779" started-at="2021-11-28T14:59:56 IST" finished-at="2021-11-28T15:00:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy] but found [Rahul Shetty Academ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy] but found [Rahul Shetty Academ]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at demo.Home.validateTitle(Home.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
      </class> <!-- demo.Home -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
